### PR TITLE
Add first version of molecule test config

### LINKED ISSUE #4: Add molecule test and integrate them with travis
It could be nice to test your role with molecule and run through travis.

### PR DESCRIPTION
**Pull request by l00ptr**
Add a minimal config for molecule to test the LemonLDAP::NG on Debian
stable and CentOS 8. Currently those tests should be run by hand and are
not executed by any CI.

### CODE REVIEW

**Comment by l00ptr** [comment]
For your information, the last action run :  https://github.com/l00ptr/ansible-lemonldapng/actions/runs/1422284723

**Comment by coudot** [comment]
@l00ptr is this PR ready to review and merge?

**Comment by l00ptr** [comment]
Hi @coudot, yes it's ready for a first review :)

**Comment by l00ptr** [comment]
any news about this PR ?

**Comment by coudot** [comment]
Sorry, we'll try to review it soon

**Review by faust64 — APPROVED** [review]
LGTM

**Comment by coudot** [comment]
Thanks @faust64 for the review and @l00ptr for your contribution!

**Pull request merged**
